### ISSUE TITLE
test error.

### ISSUE THREAD

**Issue by tiexuedanxin** [GeeeG/CloudPose#4]
hello, I have trained a model use your dataset, but when i test the model  the following error occured,could you help me, thanks.

Traceback (most recent call last):
  File "/mnt/data/heyong/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/mnt/data/heyong/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/mnt/data/heyong/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):

  File "/mnt/data/heyong/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/mnt/data/heyong/PycharmProjects/CloudPose-master/data_process_tools.py", line 91, in FPS_random
    first_idx = random.randint(0, upper_bound)

  File "/mnt/data/heyong/anaconda3/envs/tf/lib/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)

  File "/mnt/data/heyong/anaconda3/envs/tf/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))

ValueError: empty range for randrange() (0,0, 0)

	 [[{{node PyFunc}} = PyFunc[Tin=[DT_FLOAT, DT_INT32], Tout=[DT_INT64], token="pyfunc_0", _device="/device:CPU:0"](boolean_mask/GatherV2, PyFunc/input_1)]]
	 [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?], <unknown>, [?], <unknown>, <unknown>], output_types=[DT_INT64, DT_FLOAT, DT_INT64, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorFromStringHandleV2)]]
	 [[{{node Reshape/_133}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_277_Reshape", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_6d_pose.py", line 320, in <module>
    hyperparameters=hyperparameters)
  File "object_6d_pose.py", line 228, in setup_graph
    eval_graph(sess, ops, test_handle)
  File "object_6d_pose.py", line 245, in eval_graph
    feed_dict=feed_dict)
  File "/mnt/data/heyong/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/mnt/data/heyong/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/mnt/data/heyong/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/mnt/data/heyong/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):

  File "/mnt/data/heyong/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/mnt/data/heyong/PycharmProjects/CloudPose-master/data_process_tools.py", line 91, in FPS_random
    first_idx = random.randint(0, upper_bound)

  File "/mnt/data/heyong/anaconda3/envs/tf/lib/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)

  File "/mnt/data/heyong/anaconda3/envs/tf/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))

ValueError: empty range for randrange() (0,0, 0)

	 [[{{node PyFunc}} = PyFunc[Tin=[DT_FLOAT, DT_INT32], Tout=[DT_INT64], token="pyfunc_0", _device="/device:CPU:0"](boolean_mask/GatherV2, PyFunc/input_1)]]
	 [[node IteratorGetNext (defined at object_6d_pose.py:125)  = IteratorGetNext[output_shapes=[[?], <unknown>, [?], <unknown>, <unknown>], output_types=[DT_INT64, DT_FLOAT, DT_INT64, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorFromStringHandleV2)]]
	 [[{{node Reshape/_133}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_277_Reshape", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by GeeeG** [comment]
Looks like something with the FPS with random starting point.
Could you try this to see if it fix the problem:
In the "data_process_tools.py", function "FPS_random", comment the 3rd and 4th line, and set first_idx as 0

def FPS_random(pts, K):
    farthest_pts = np.zeros((K, 3))
    farthest_pts_idx = np.zeros(K)
    # upper_bound = pts.shape[0] - 1
    # first_idx = random.randint(0, upper_bound)
    first_idx = 0
........................
